### ISSUE TITLE
Invalid protocol exception on client side when use_list=True

### ISSUE THREAD

**Issue by Ferenc-** [studio-ousia/mprpc#34]
If I try to get a list as result, I keep getting the following exception:

```
client = RPCClient('127.0.0.1', RPC_PORT, unpack_params=dict(use_list=True))
client.call('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mprpc/client.pyx", line 147, in mprpc.client.RPCClient.call (mprpc/client.c:2680)
mprpc.exceptions.RPCProtocolError: Invalid protocol
```
If I keep using tuple, then everything works fine.

**Comment by ikuyamada** [comment]
Would you please provide a source code that reproduces the results?

**Comment by Ferenc-** [comment]
Server:

```
#!/usr/bin/env python3

from gevent.server import StreamServer
from mprpc import RPCServer


class FooServer(RPCServer):
    def foo(self, x, y):
        return [x, y]


server = StreamServer(('127.0.0.1', 6000), FooServer())
server.serve_forever()
```
Client:

```
#!/usr/bin/env python3

from mprpc import RPCClient

client = RPCClient('127.0.0.1', 6000, unpack_params=dict(use_list=True))
client.call('foo', 1, 2)
```

**Comment by ikuyamada** [comment]
Thank you for your code! The issue was successfully reproduced.
The commit above should fix this issue.

**Comment by ikuyamada** [comment]
@Ferenc- a new version (v0.1.11) that contains this fix has been uploaded to PyPi. Thank you for your report.

**Comment by Ferenc-** [comment]
@ikuyamada Thank you for the quick fix! Keep up the great work!
