### ISSUE TITLE
Does not seem to work with py2

### ISSUE THREAD

**Issue by kootenpv** [studio-ousia/mprpc#36]
Does this package support python 2? It does not appear so for me:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/spacy_api/client.py", line 77, in __init__
    self.rpc = RPCClient(host, port)
  File "mprpc/client.pyx", line 67, in mprpc.client.RPCClient.__init__ (mprpc/client.c:1339)
TypeError: argument after ** must be a mapping, not NoneType
```

Note that I call it with the args "127.0.0.1" and 9033

**Comment by ikuyamada** [comment]
I found a serious bug in client.pyx. I've fixed this in the latest commit.

**Comment by kootenpv** [comment]
Is it also already on pypi?

**Comment by ikuyamada** [comment]
Yes, it is already on PyPI.

**Comment by kootenpv** [comment]
I had to delete .tox, but now indeed it works! Great, thanks!
